<?php

/**
 * Implements hook_menu().
 */
function culturefeed_uitpas_promotions_menu() {
  $items['admin/config/culturefeed/uitpas/uitpas-promotions'] = array(
    'title' => t('UiTPAS promotions search'),
    'description' => t('Change settings for UiTPAS promotions search'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('culturefeed_uitpas_promotions_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'culturefeed_uitpas_promotions.admin.inc',
  );

  $items['promotions'] = array(
    'title' => t('Search UiTPAS promotions'),
    'title callback' => '',
    'page callback' => 'culturefeed_uitpas_promotions_search',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'culturefeed_uitpas_promotions.pages.inc'
  );

  $items['culturefeed/profile/uitpas/promotions'] = array(
    'title' => t('Search my UiTPAS promotions'),
    'title callback' => '',
    'page callback' => 'culturefeed_uitpas_promotions_profile_search',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'culturefeed_uitpas_promotions.pages.inc'
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function culturefeed_uitpas_promotions_theme() {
  return array(
    'culturefeed_uitpas_promotions_search' => array(
      'variables' => array(
        'url_uitpas' => NULL,
        'url_uitdatabank' => NULL,
        'fuzzy_search' => NULL,
        'placeholder' => NULL,
        'filter_cardsystem' => NULL,
        'card_systems' => NULL,
        'last_chance' => NULL,
        'spotlight' => NULL
      ),
      'template' => 'theme/culturefeed-uitpas-promotions-search',
      'file' => 'theme/theme.inc'
    ),
  );
}